namespace Ligth.Models;

public class CasamentoReligioso
{
    public int id { get; set; }
    public string livro { get; set; }
    public string numero { get; set; }
    public string pagina { get; set; }
    public string registro { get; set; }
    public string datareg { get; set; }
    public string diaregcal { get; set; }
    public string mesregcal { get; set; }
    public string anoregcal { get; set; }
    public string diaregext { get; set; }
    public string mesregext { get; set; }
    public string anoregext { get; set; }
    public string datadia { get; set; }
    public string diadiacal { get; set; }
    public string mesdiacal { get; set; }
    public string anodiacal { get; set; }
    public string diadiaext { get; set; }
    public string mesdiaext { get; set; }
    public string anodiaext { get; set; }
    public string datahab { get; set; }
    public string diahabcal { get; set; }
    public string meshabcal { get; set; }
    public string anohabcal { get; set; }
    public string diahabext { get; set; }
    public string meshabext { get; set; }
    public string anohabext { get; set; }
    public string datapro { get; set; }
    public string diaprocal { get; set; }
    public string mesprocal { get; set; }
    public string anoprocal { get; set; }
    public string diaproext { get; set; }
    public string mesproext { get; set; }
    public string anoproext { get; set; }
    public string datacas { get; set; }
    public string diacascal { get; set; }
    public string mescascal { get; set; }
    public string anocascal { get; set; }
    public string diacasext { get; set; }
    public string mescasext { get; set; }
    public string anocasext { get; set; }
    public string horacas { get; set; }
    public string regime { get; set; }
    public string igreja { get; set; }
    public string padre { get; set; }
    public string ptestemunha { get; set; }
    public string stestemunha { get; set; }
    public string processo { get; set; }
    public string noivo { get; set; }
    public string nacnoivo { get; set; }
    public string natnoivo { get; set; }
    public string estcivnoivo { get; set; }
    public string pronoivo { get; set; }
    public string datanoivo { get; set; }
    public string dianoivocal { get; set; }
    public string mesnoivocal { get; set; }
    public string anonoivocal { get; set; }
    public string dianoivoext { get; set; }
    public string mesnoivoext { get; set; }
    public string anonoivoext { get; set; }
    public string endnoivo { get; set; }
    public string idadenoivo { get; set; }
    public string idadenoivoext { get; set; }
    public string painoivo { get; set; }
    public string natpainoivo { get; set; }
    public string estcivpainoivo { get; set; }
    public string propainoivo { get; set; }
    public string endpainoivo { get; set; }
    public string maenoivo { get; set; }
    public string natmaenoivo { get; set; }
    public string estcivmaenoivo { get; set; }
    public string promaenoivo { get; set; }
    public string endmaenoivo { get; set; }
    public string noiva { get; set; }
    public string nacnoiva { get; set; }
    public string natnoiva { get; set; }
    public string estcivnoiva { get; set; }
    public string pronoiva { get; set; }
    public string datanoiva { get; set; }
    public string dianoivacal { get; set; }
    public string mesnoivacal { get; set; }
    public string anonoivacal { get; set; }
    public string dianoivaext { get; set; }
    public string mesnoivaext { get; set; }
    public string anonoivaext { get; set; }
    public string endnoiva { get; set; }
    public string idadenoiva { get; set; }
    public string idadenoivaext { get; set; }
    public string painoiva { get; set; }
    public string natpainoiva { get; set; }
    public string estcivpainoiva { get; set; }
    public string propainoiva { get; set; }
    public string endpainoiva { get; set; }
    public string maenoiva { get; set; }
    public string natmaenoiva { get; set; }
    public string estcivmaenoiva { get; set; }
    public string promaenoiva { get; set; }
    public string endmaenoiva { get; set; }
    public string nomenovonoiva { get; set; }
    public string comarca { get; set; }
    public string oficial { get; set; }
    public string cartoriocom { get; set; }
    public string livronasccas { get; set; }
    public string numlivro { get; set; }
    public string folhalivro { get; set; }
    public string numtermo { get; set; }
    public string datatermo { get; set; }
    public string oficartorio { get; set; }
    public string obs1 { get; set; }
    public string obs2 { get; set; }
    public string nomenovonoivo { get; set; }
}