namespace Ligth.Models;

public class CasamentoCivil
{
    public int id { get; set; }
    public string livro { get; set; }
    public string numero { get; set; }
    public string pagina { get; set; }
    public string registro { get; set; }
    public string datacas { get; set; }
    public string diacascal { get; set; }
    public string mescascal { get; set; }
    public string anocascal { get; set; }
    public string diacasext { get; set; }
    public string mescasext { get; set; }
    public string anocasext { get; set; }
    public string regime { get; set; }
    public string juiz { get; set; }
    public string dataedi { get; set; }
    public string diaedical { get; set; }
    public string mesedical { get; set; }
    public string anoedical { get; set; }
    public string diaediext { get; set; }
    public string mesediext { get; set; }
    public string anoediext { get; set; }
    public string datacer { get; set; }
    public string diacercal { get; set; }
    public string mescercal { get; set; }
    public string anocercal { get; set; }
    public string diacerext { get; set; }
    public string mescerext { get; set; }
    public string anocerext { get; set; }
    public string ptestemunha { get; set; }
    public string stestemunha { get; set; }
    public string noivo { get; set; }
    public string nacnoivo { get; set; }
    public string natnoivo { get; set; }
    public string pronoivo { get; set; }
    public string estcivnoivo { get; set; }
    public string endnoivo { get; set; }
    public string datanoivo { get; set; }
    public string dianoivocal { get; set; }
    public string mesnoivocal { get; set; }
    public string anonoivocal { get; set; }
    public string dianoivoext { get; set; }
    public string mesnoivoext { get; set; }
    public string anonoivoext { get; set; }
    public string idadenoivo { get; set; }
    public string idadenoivoext { get; set; }
    public string painoivo { get; set; }
    public string natpainoivo { get; set; }
    public string estcivpainoivo { get; set; }
    public string propainoivo { get; set; }
    public string endpainoivo { get; set; }
    public string maenoivo { get; set; }
    public string natmaenoivo { get; set; }
    public string estcivmaenoivo { get; set; }
    public string promaenoivo { get; set; }
    public string endmaenoivo { get; set; }
    public string noiva { get; set; }
    public string nacnoiva { get; set; }
    public string natnoiva { get; set; }
    public string estcivnoiva { get; set; }
    public string pronoiva { get; set; }
    public string datnasnoiva { get; set; }
    public string dianoivacal { get; set; }
    public string mesnoivacal { get; set; }
    public string anonoivacal { get; set; }
    public string dianoivaext { get; set; }
    public string mesnoivaext { get; set; }
    public string anonoivaext { get; set; }
    public string endnoiva { get; set; }
    public string idadenoiva { get; set; }
    public string idadenoivaext { get; set; }
    public string nomenovonoiva { get; set; }
    public string painoiva { get; set; }
    public string natpainoiva { get; set; }
    public string estcivpainoiva { get; set; }
    public string propainoiva { get; set; }
    public string endpainoiva { get; set; }
    public string maenoiva { get; set; }
    public string natmaenoiva { get; set; }
    public string estcivmaenoiva { get; set; }
    public string promaenoiva { get; set; }
    public string endmaenoiva { get; set; }
    public string obs1 { get; set; }
    public string comarca { get; set; }
    public string oficial { get; set; }
    public string horacasamento { get; set; }
    public string local_casament { get; set; }
    public string diapetcal { get; set; }
    public string mespetcal { get; set; }
    public string anopetcal { get; set; }
    public string diahabcal { get; set; }
    public string meshabcal { get; set; }
    public string anohabcal { get; set; }
    public string diareqcal { get; set; }
    public string mesreqcal { get; set; }
    public string anoreqcal { get; set; }
    public string nacptest { get; set; }
    public string endptest { get; set; }
    public string estcivptest { get; set; }
    public string proptest { get; set; }
    public string idadeptest { get; set; }
    public string nacstest { get; set; }
    public string endstest { get; set; }
    public string estcivstest { get; set; }
    public string prostest { get; set; }
    public string idadestest { get; set; }
    public string consentimento { get; set; }
    public string datapet { get; set; }
    public string mespetext { get; set; }
    public string datahab { get; set; }
    public string meshabext { get; set; }
    public string datareq { get; set; }
    public string mesreqext { get; set; }
    public string nomenovonoivo { get; set; }
    public string cartoriocom { get; set; }
    public string livronasccas { get; set; }
    public string numlivro { get; set; }
    public string folhalivro { get; set; }
    public string numtermo { get; set; }
    public string datatermo { get; set; }
    public string servidorconf { get; set; }
    public string averbacao { get; set; }
    public string oficialcom { get; set; }
    public string obs2 { get; set; }
    public string noiva2 { get; set; }
}