namespace Ligth.Models;

public class Obito
{
    public int id { get; set; }
    public string livro { get; set; }
    public string numliv { get; set; }
    public string numpag { get; set; }
    public string registro { get; set; }
    public string dataregistro { get; set; }
    public string diaregcal { get; set; }
    public string mesregcal { get; set; }
    public string anoregcal { get; set; }
    public string nome { get; set; }
    public string sexo { get; set; }
    public string idade { get; set; }
    public string estadocivil { get; set; }
    public string profissao { get; set; }
    public string endereco { get; set; }
    public string cidade { get; set; }
    public string estado { get; set; }
    public string pai { get; set; }
    public string datamorte { get; set; }
    public string diamorcal { get; set; }
    public string mesmorcal { get; set; }
    public string anomorcal { get; set; }
    public string horamorte { get; set; }
    public string horacal { get; set; }
    public string mincal { get; set; }
    public string cemiterio { get; set; }
    public string declarante { get; set; }
    public string natdec { get; set; }
    public string profdec { get; set; }
    public string estcivdec { get; set; }
    public string comarca { get; set; }
    public string oficial { get; set; }
    public string datacert { get; set; }
    public string diacal { get; set; }
    public string mescal { get; set; }
    public string anocal { get; set; }
    public string justifica1 { get; set; }
    public string justifica2 { get; set; }
    public string justifica3 { get; set; }
    public string justifica4 { get; set; }
    public string justifica6 { get; set; }
    public string justifica7 { get; set; }
    public string cartorioreg { get; set; }
    public string livronasccas { get; set; }
    public string folhanascimen { get; set; }
    public string termonascimen { get; set; }
    public string numlivro { get; set; }
    public string datanascimento { get; set; }
    public string averbacao { get; set; }
    public string doo { get; set; }
    public string cidadecem { get; set; }
    public string estadocem { get; set; }
    public string rg { get; set; }
    public string oe { get; set; }
    public string ufrg { get; set; }
    public string ibge { get; set; }
    public string diaregext { get; set; }
    public string mesregext { get; set; }
    public string anoregext { get; set; }
    public string mae { get; set; }
    public string diamorext { get; set; }
    public string mesmorext { get; set; }
    public string anomorext { get; set; }
    public string horaext { get; set; }
    public string minext { get; set; }
    public string local { get; set; }
    public string causa1 { get; set; }
    public string causa2 { get; set; }
    public string doutor { get; set; }
    public string obs1 { get; set; }
    public string mesext { get; set; }
    public string datanascimen { get; set; }
    public string oficialcomuni { get; set; }
    public string cpf { get; set; }
    public string tituloeleitor { get; set; }
    public string ct { get; set; }
    public string se { get; set; }
    public string ufct { get; set; }
    public string nit { get; set; }
    public string justifica5 { get; set; }
    public string beneficio1 { get; set; }
    public string justifica8 { get; set; }
}